# Generated by Django 3.1.4 on 2020-12-10 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Загловок')),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 12, 10, 0, 48, 23, 939760, tzinfo=utc), verbose_name='Дата публикации')),
                ('post_type_image', models.SmallIntegerField(verbose_name='Тип поста')),
                ('description', models.CharField(max_length=500, verbose_name='Описание поста')),
                ('content', models.TextField(verbose_name='Содержание поста')),
            ],
        ),
    ]
