# Generated by Django 3.1.4 on 2020-12-10 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 10, 0, 48, 58, 866331, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
