# Generated by Django 3.1.4 on 2020-12-11 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201210_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type_image',
            field=models.SmallIntegerField(choices=[(1, 'Новости'), (2, 'Акции'), (3, 'Развлекательная информация')], verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 12, 44, 9, 343203, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
