# Generated by Django 3.1.4 on 2020-12-11 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201211_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 13, 57, 11, 745205, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
