# Generated by Django 3.1.4 on 2020-12-11 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201211_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 14, 13, 33, 191201, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
