# Generated by Django 3.1.4 on 2020-12-11 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('number', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, verbose_name='Номер медкарты')),
                ('started_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заведения медкарты')),
            ],
            options={
                'ordering': ['started_date'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата внесения записи')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата посещения')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок записи')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание записи')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_cards.medicalcard')),
            ],
            options={
                'ordering': ['record_date'],
            },
        ),
    ]
